#!/bin/sh

mode=$1
shift >/dev/null 2>&1

if [[ $mode == "build" || $mode == "b" ]]; then
    echo -e 'running the following command:\n\t$ podman build -t squid-game .\n'
    podman build -t squid-game .

elif [[ $mode == "run" || $mode == "r" ]]; then
    echo -e "running the following command:\n\t$ podman run -it --rm squid-game -c "./squid-bin $@"\n"
    podman run -it --rm squid-game -c "./squid-bin $@"

elif [[ $mode == "keep-run" || $mode == "keep" || $mode == "k" ]]; then
    echo -e "running the following command:\n\t$ podman run -it squid-game -c "./squid-bin $@"\n"
    podman run -it squid-game -c "./squid-bin $@"

else
    echo -e 'usage: ./squid [build|b]                # build docker'
    echo -e '  or:  ./squid [run|r] [args ...]       # run and remove image'
    echo -e '  or:  ./squid [keep-run|k] [args ...]  # run and do not remove image\n'
fi
