---
- name: Setup for all hosts
  hosts: all
  tasks:
    - name: Deploy bin on all hosts
      copy:
        src: "../squid-bin"
        dest: "$HOME/squid-game/squid-bin"
        mode: "0755"

    - name: Kill current program related processes on all hosts
      shell: |
        pkill --full --echo squid-bin || echo "Process wasn't running"

- name: Start leader
  hosts: leaders
  tasks:
    - name: Run on background
      shell:
        cmd: "sleep 5 && ./squid-bin leader &"
        chdir: "$HOME/squid-game"

- name: Start namenode
  hosts: namenodes
  tasks:
    - name: Run on background
      shell:
        cmd: "sleep 5 && nohup ./squid-bin namenode >namenode.out &"
        chdir: "$HOME/squid-game"

- name: Start datanodes
  hosts: datanodes
  tasks:
    - name: Run on background
      shell:
        cmd: "sleep 5 && nohup ./squid-bin datanode >datanode.out &"
        chdir: "$HOME/squid-game"

- name: Start pool
  hosts: pool
  tasks:
    - name: Run on background
      shell:
        cmd: "sleep 5 && nohup ./squid-bin pool >pool.out &"
        chdir: "$HOME/squid-game"

- name: Start bot player
  hosts: players
  tasks:
    - name: Start resumed player on background (attach to it with fg)
      shell: |
        sleep 5 && ./squid-bin human &
      args:
        chdir: "$HOME/squid-game"
