---
- name: Setup for all hosts
  hosts: all
  tasks:
    - name: Deploy bin on all hosts
      copy:
        src: "../squid-bin"
        dest: "$HOME/squid-game/squid-bin"
        mode: "0755"

    - name: Kill current program related processes on all hosts
      shell: |
        pkill --echo squid-bin || echo "Process wasn't running"

- name: Start leader
  hosts: leaders
  tasks:
    - name: Run on background
      shell:
        cmd: "./squid-bin leader &"
        chdir: "$HOME/squid-game"

- name: Start namenode
  hosts: namenodes
  tasks:
    - name: Run on background
      shell:
        cmd: "./squid-bin namenode &"
        chdir: "$HOME/squid-game"

- name: Start datanodes
  hosts: datanodes
  tasks:
    - name: Run on background
      shell:
        cmd: "./squid-bin datanode &"
        chdir: "$HOME/squid-game"

- name: Start pool
  hosts: pool
  tasks:
    - name: Run on background
      shell:
        cmd: "./squid-bin pool &"
        chdir: "$HOME/squid-game"

- name: Start bot player
  hosts: players
  tasks:
    - name: Start resumed player on background (attach to it with fg)
      shell: |
        ./squid-bin human &
        kill -STOP $!
      args:
        chdir: "$HOME/squid-game"
