---
- name: Setup for all hosts
  hosts: all
  tasks:
    - name: Deploy bin on all hosts
      copy:
        src: "../squid-bin"
        dest: "$HOME/squid-game/squid-bin"
        mode: "0755"

    - name: Kill current program related processes on all hosts
      shell: |
        for pid in $(pgrep -f squid-bin | grep -v -x $$); do
          kill $pid || echo "Process wasn't running";
        done

- name: Start datanodes
  hosts: datanodes
  tasks:
    - name: Run on background
      shell:
        cmd: "(./squid-bin datanode &)"
        chdir: "$HOME/squid-game"
      async: 30
      poll: 0

- name: Start namenode
  hosts: namenodes
  tasks:
    - name: Run on background
      shell:
        cmd: "(sleep 5 && ./squid-bin namenode &)"
        chdir: "$HOME/squid-game"
      async: 30
      poll: 0

- name: Start pool
  hosts: pool
  tasks:
    - name: Run on background
      shell:
        cmd: "(sleep 5 && ./squid-bin pool &)"
        chdir: "$HOME/squid-game"
      async: 30
      poll: 0

- name: Start leader
  hosts: leaders
  tasks:
    - name: Run on background
      shell:
        cmd: |
          tmux new-session -A -s leader \; send -t leader "./squid-bin leader &" ENTER \; detach -s leader
        chdir: "$HOME/squid-game"
      async: 30
      poll: 0

- name: Start bot player
  hosts: players
  tasks:
    - name: Start player on background (attach to it with fg)
      shell: |
        tmux new-session -A -s player \; send -t player "./squid-bin player &" ENTER \; detach -s player
      args:
        chdir: "$HOME/squid-game"
      async: 30
      poll: 0
