name: pr-branch-check

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up protobuf + gRPC
      run: |
        curl -LO $PB_URL/$PROTO_VER/$ZIP_NAME
        unzip $ZIP_NAME -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
      env:
        PB_URL: "https://github.com/protocolbuffers/protobuf/releases/download"
        PROTO_VER: "v3.19.0"
        ZIP_NAME: "protoc-3.19.0-linux-x86_64.zip"

    - name: Compile protobufs
      run: |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        $(find ./ -name "*.proto")

    - name: Build
      run: go build -v ./...
