name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-hosts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up protobuf + gRPC
      run: |
        curl -LO $PB_URL/$PROTO_VER/$ZIP_NAME
        unzip $ZIP_NAME -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
      env:
        PB_URL: "https://github.com/protocolbuffers/protobuf/releases/download"
        PROTO_VER: "v3.19.0"
        ZIP_NAME: "protoc-3.19.0-linux-x86_64.zip"

    - name: Compile protobufs
      run: |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        $(find ./ -name "*.proto")

    - name: Build Project
      run: |
        for dir in leader namenode datanode player pool; do \
            go build -o $dir/$dir -v $dir/main.go; \
        done  

    - name: Deploy
      uses: dawidd6/action-ansible-playbook@v2.5.0
      env:
        JUMP_HOST: "alumno@2.tcp.ngrok.io:18885"
      with:
        playbook: ./ansible/deploy.yml
        key: ${{ secrets.ANSIBLE_KEY }}
        known_hosts: |
          |1|5u3cmmBz0LM5ouxNRKhrZbKi0uM=|SPd+TOg3mYvQBfZx0TxI5/HF8T0= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3EIMtrzlDTytZMwF3Wg8A7G/ceuijd1y4Y1wFm4fstoU4ySxtypQyqLqVyDkrgOv4KFna+0/1DvcNWrnSlsO8TbttY/O3dyInwcDXiMStRq9O6eb6Egf2ay64NTRZ4pEeK2R+VP1WASvlvxUzb4F+9i9EOu6Ap6Qq9aNjLlsmXgGnVQGACruK213J/fwfTHkJmlMWy4TNPWjLJxd26F8fQYXep4yZmRLReEVmV8bN5wAd/8UdLMyzxHwEBSb+v+bM/rwopJ02wKHpswa5bg5IQGTqc5wpea/6ckfpBRYgupesHGYCLJ1Va2NK/fbPnFV+E/7j6Ty0pL+fMCzxGZl/
          |1|q+prMQaZYXmvqkgH7i1DouLz69M=|xsPWSUz+MiVqDFL/gHJcb4mZ91w= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKHr/lSRC6Ul3LaoZUs8/2K3Zjqq/Vl+lqUHVnE4+VubFJR6UcQmpEBWlEkWKvIavDGTOLQnnAKJZ4uG4EaqkE=
          |1|wMQeKcKpPnzjJRotTtb7Dxr/iTw=|nlU+VgKz8Yc3fVjeEwe1rLV6WWI= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINn0F1FHddthgnv6KMXirkKXjk21f/yrfj2H+D+z6eQ6
          |1|UNNTOPqYHEmD9XV8CXne/Xh9xmQ=|/n4CKnsTB0o9e3QAPgPdhLMrieQ= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3EIMtrzlDTytZMwF3Wg8A7G/ceuijd1y4Y1wFm4fstoU4ySxtypQyqLqVyDkrgOv4KFna+0/1DvcNWrnSlsO8TbttY/O3dyInwcDXiMStRq9O6eb6Egf2ay64NTRZ4pEeK2R+VP1WASvlvxUzb4F+9i9EOu6Ap6Qq9aNjLlsmXgGnVQGACruK213J/fwfTHkJmlMWy4TNPWjLJxd26F8fQYXep4yZmRLReEVmV8bN5wAd/8UdLMyzxHwEBSb+v+bM/rwopJ02wKHpswa5bg5IQGTqc5wpea/6ckfpBRYgupesHGYCLJ1Va2NK/fbPnFV+E/7j6Ty0pL+fMCzxGZl/
          |1|lUlUZmxE7EBm52isHDPXGzXAWEw=|4PsgDYzQbi05IMUuYjAOSQs0mow= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKHr/lSRC6Ul3LaoZUs8/2K3Zjqq/Vl+lqUHVnE4+VubFJR6UcQmpEBWlEkWKvIavDGTOLQnnAKJZ4uG4EaqkE=
          |1|mJ0SBxzA6re7pMKcp3E+WVt4zcw=|/SXIcpBgGOiA8PqZuvSWg/ydf+c= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINn0F1FHddthgnv6KMXirkKXjk21f/yrfj2H+D+z6eQ6
          |1|8YSOg0obwf9qsExRZWubIlgM2Dg=|/CWmrr9oorBrGKYWxJrOXttlfXQ= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINn0F1FHddthgnv6KMXirkKXjk21f/yrfj2H+D+z6eQ6
          |1|15bcFemLeTgnJLJSYrVc/g493Ms=|MP7ldetQzygjmN4MY7ALd08MyFU= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3EIMtrzlDTytZMwF3Wg8A7G/ceuijd1y4Y1wFm4fstoU4ySxtypQyqLqVyDkrgOv4KFna+0/1DvcNWrnSlsO8TbttY/O3dyInwcDXiMStRq9O6eb6Egf2ay64NTRZ4pEeK2R+VP1WASvlvxUzb4F+9i9EOu6Ap6Qq9aNjLlsmXgGnVQGACruK213J/fwfTHkJmlMWy4TNPWjLJxd26F8fQYXep4yZmRLReEVmV8bN5wAd/8UdLMyzxHwEBSb+v+bM/rwopJ02wKHpswa5bg5IQGTqc5wpea/6ckfpBRYgupesHGYCLJ1Va2NK/fbPnFV+E/7j6Ty0pL+fMCzxGZl/
          |1|Gu9NxWkcN3CpVtocYElOsnLhgfA=|EYv8fZzM/H0FntfNG+5J9SiybHA= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKHr/lSRC6Ul3LaoZUs8/2K3Zjqq/Vl+lqUHVnE4+VubFJR6UcQmpEBWlEkWKvIavDGTOLQnnAKJZ4uG4EaqkE=
          |1|0UM4fqgoG78MrBrRXGE4ILk7KDw=|o/tnOf7WWORu4eABjJ6nnEM9sSc= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKHr/lSRC6Ul3LaoZUs8/2K3Zjqq/Vl+lqUHVnE4+VubFJR6UcQmpEBWlEkWKvIavDGTOLQnnAKJZ4uG4EaqkE=
          |1|6jrv2MoQGev693tVMUNtncQowfQ=|1m3L5goUt1I46TgQnE48tWbvUG4= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3EIMtrzlDTytZMwF3Wg8A7G/ceuijd1y4Y1wFm4fstoU4ySxtypQyqLqVyDkrgOv4KFna+0/1DvcNWrnSlsO8TbttY/O3dyInwcDXiMStRq9O6eb6Egf2ay64NTRZ4pEeK2R+VP1WASvlvxUzb4F+9i9EOu6Ap6Qq9aNjLlsmXgGnVQGACruK213J/fwfTHkJmlMWy4TNPWjLJxd26F8fQYXep4yZmRLReEVmV8bN5wAd/8UdLMyzxHwEBSb+v+bM/rwopJ02wKHpswa5bg5IQGTqc5wpea/6ckfpBRYgupesHGYCLJ1Va2NK/fbPnFV+E/7j6Ty0pL+fMCzxGZl/
          |1|nZAekLIXmy4dV7FYGIoYiCwSVIU=|v4p3f5Kc71RoSz147vKODccjr2o= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINn0F1FHddthgnv6KMXirkKXjk21f/yrfj2H+D+z6eQ6          
          |1|qQdRJSl+Y2s1pZSZPFrQEwr9c+Y=|ZNNBhv3cI6qEetXf7OfoEuFplqo= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3EIMtrzlDTytZMwF3Wg8A7G/ceuijd1y4Y1wFm4fstoU4ySxtypQyqLqVyDkrgOv4KFna+0/1DvcNWrnSlsO8TbttY/O3dyInwcDXiMStRq9O6eb6Egf2ay64NTRZ4pEeK2R+VP1WASvlvxUzb4F+9i9EOu6Ap6Qq9aNjLlsmXgGnVQGACruK213J/fwfTHkJmlMWy4TNPWjLJxd26F8fQYXep4yZmRLReEVmV8bN5wAd/8UdLMyzxHwEBSb+v+bM/rwopJ02wKHpswa5bg5IQGTqc5wpea/6ckfpBRYgupesHGYCLJ1Va2NK/fbPnFV+E/7j6Ty0pL+fMCzxGZl/
          |1|tIWy5hy8jldg7rJaHiFhuSOxdSg=|UlOTb266fx5Xq3VHB9jHrqw/Tas= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIKHr/lSRC6Ul3LaoZUs8/2K3Zjqq/Vl+lqUHVnE4+VubFJR6UcQmpEBWlEkWKvIavDGTOLQnnAKJZ4uG4EaqkE=
          |1|ll/q56DK4JqlkRjgLLHvOSe9M2w=|Or5Sf49zhha1DismEMy6VNr2xuk= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINn0F1FHddthgnv6KMXirkKXjk21f/yrfj2H+D+z6eQ6
        options: |
          -i ./ansible/hosts.ini
          -vvvv
