name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-hosts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.15

    - name: Set up protobuf
      run: |
        apt install -y protobuf-compiler
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

    - name: Compile protobufs
      run: |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        $(find ./ -name "*.proto")
      env:
        PATH: "$PATH:$(go env GOPATH)/bin"

    - name: Build Project
      run: go build -o ./squid-bin -v ./...

    - name: Deploy
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        playbook: ./ansible/deploy.yml
        key: ${{ secrets.ANSIBLE_KEY }}
        inventory: ./ansible/hosts.ini
      env:
        JUMP_HOST: ${{ secrets.BASTION_HOST }}
