name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-hosts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up protobuf + gRPC
      run: |
        curl -LO $PB_URL/$PROTO_VER/$ZIP_NAME
        unzip $ZIP_NAME -d $HOME/.local
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        
      env:
        PB_URL: "https://github.com/protocolbuffers/protobuf/releases/download"
        PROTO_VER: "v3.19.0"
        ZIP_NAME: "protoc-3.19.0-linux-x86_64.zip"

    - name: Compile protobufs
      run: |
        protoc --go_out=. --go_opt=paths=source_relative \
        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
        $(find ./ -name "*.proto")

    - name: Build Project
      run: |
        for dir in leader namenode datanode player pool; do \
            go build -o $dir/$dir -v $dir/main.go; \
        done  

    - name: Add key to ssh-agent
      run: |
        eval $(ssh-agent)
        ssh-add - <<< "$SSH_KEY"
      env:
        SSH_KEY: ${{ secrets.ANSIBLE_KEY }}

    - name: Deploy
      uses: dawidd6/action-ansible-playbook@v2.5.0
      env:
        JUMP_HOST: "alumno@2.tcp.ngrok.io:18885"
      with:
        playbook: ./ansible/deploy.yml
        options: |
          -i ./ansible/hosts.ini
          -vvvv
